# Generated by Django 3.1.5 on 2021-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_debit',
        ),
        migrations.AlterField(
            model_name='customer',
            name='total',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
